version: '3'

services:
  postgres:
    container_name: postgres
    image: 'postgres:10.10-alpine'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'web'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

volumes:
  postgres:
